# Generated by Django 5.1.2 on 2024-10-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('modified_at', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('modified_at', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_at', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('current_owner', models.CharField(max_length=100)),
                ('demo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'Hold'), ('2', 'Inprogress'), ('3', 'Completed')], max_length=100)),
                ('POC', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('Git_link', models.URLField(blank=True)),
                ('Application_Doc', models.URLField(blank=True)),
                ('Research_Doc', models.URLField(blank=True)),
                ('Deployment', models.DateTimeField(auto_now_add=True)),
                ('code_review', models.TextField(default='not yet done')),
                ('contact_owner', models.EmailField(blank=True, max_length=254, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.domain')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('techstack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.technology')),
            ],
        ),
    ]
