# Generated by Django 5.1.2 on 2024-10-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_status_alter_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('1', 'Hold'), ('2', 'Inprogress'), ('3', 'Completed')], max_length=100),
        ),
    ]
