# Generated by Django 5.1.2 on 2024-10-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_projects_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
    ]
