# Generated by Django 5.1.2 on 2024-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_projects_techstack_projects_techstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='department',
        ),
        migrations.AddField(
            model_name='projects',
            name='department',
            field=models.ManyToManyField(to='app1.department'),
        ),
    ]
