# Generated by Django 5.1.2 on 2024-10-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_projects_department_projects_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='department',
        ),
        migrations.AddField(
            model_name='projects',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
            preserve_default=False,
        ),
    ]
